[package]
name = "scepter-system-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
quick-xml = { version = "0.37.4", features = ["encoding"] }
egui = "0.31.1"
eframe = { version = "0.31.1", features = ["persistence", "ron"] }
egui-file-dialog = "0.9.0"
egui-snarl = { version = "0.7.1", features = ["serde"]}
egui_extras = { version = "0.31.1", features = ["image"] }
egui_material_icons = "0.3.0"
env_logger = "0.11.8"
ron = "0.9.0"
serde = { version = "1.0.219", features = ["derive"] }
reqwest = { version = "0.12.15", features = ["json", "stream", "blocking"] }
serde_json = "1.0.140"
parking_lot = "0.12.3"
thiserror = "2.0.12"
anyhow = "1.0.97"
