[package]
name = "scepter-system-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.30.0"
egui_extras = { version = "0.30.0", features = ["image"] }
egui_material_icons = { git = "https://github.com/shadow3aaa/hello_egui" }
env_logger = "0.11.6"
