[package]
name = "scepter-system-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.30.0"
egui_extras = { version = "0.30.0", features = ["image"] }
egui_material_icons = "0.2.0"
env_logger = "0.11.6"
